name = "imdb-api"

workers_dev = true
compatibility_date = "2023-02-28"
[observability.logs]
enabled = true
kv_namespaces = [
         { binding = "CACHE", id = "9c3bfee76b304f2ca224e0c41bab16a4" }
]
